# Generated by Django 3.1.7 on 2021-03-10 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0009_contentpagetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentPageTime',
            new_name='ContentPageActiveTime',
        ),
    ]
