# Generated by Django 3.1.1 on 2020-09-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_rating', '0003_auto_20171027_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='extra',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
