# Generated by Django 3.1.1 on 2020-09-30 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20171027_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='data',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='lifespan',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 0, 1, 8, 153080, tzinfo=utc), null=True),
        ),
    ]
