# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems_python', '0005_auto_20171027_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixitSubmissionObject',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems_python.Submission')),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=('problems_python.submission',),
        ),
    ]
